name: Add untriaged label

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check labels
        id: check_labels
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            const hasBugLabel = labels.includes('Bug');
            const hasUntriagedLabel = labels.includes('untriaged');
            core.setOutput('hasBugLabel', hasBugLabel);
            core.setOutput('hasUntriagedLabel', hasUntriagedLabel);

      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # 1.0.4
        if: steps.check_labels.outputs.hasBugLabel && !steps.check_labels.outputs.hasUntriagedLabel
        with:
          add-labels: 'untriaged'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
